import AppKit
import OSLog

@MainActor
final class ClipboardMonitorService {
    private static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "Orvia", category: "clipboard")
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let pasteboard: NSPasteboard
    private let storageService: ClipboardStorageService
    private let settings: AppSettings
    private let sourceBundleIDProvider: () -> String?
    private let ownBundleID = Bundle.main.bundleIdentifier?.lowercased()
    private var pollingSource: DispatchSourceTimer?
    private var lastChangeCount: Int
    private var suppressedChangeCount: Int?
    var isRunning: Bool { pollingSource != nil }

    init(
        pasteboard: NSPasteboard = .general,
        storageService: ClipboardStorageService,
        settings: AppSettings,
        sourceBundleIDProvider: @escaping () -> String? = {
            NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        }
    ) {
        self.pasteboard = pasteboard
        self.storageService = storageService
        self.settings = settings
        self.sourceBundleIDProvider = sourceBundleIDProvider
        lastChangeCount = pasteboard.changeCount

        NotificationCenter.default.addObserver(
            self, selector: #selector(handleProgrammaticWrite),
            name: .clipboardDidProgrammaticWrite, object: nil
        )
        NSWorkspace.shared.notificationCenter.addObserver(
            self, selector: #selector(handleWake),
            name: NSWorkspace.didWakeNotification, object: nil
        )
        NSWorkspace.shared.notificationCenter.addObserver(
            self, selector: #selector(handleWake),
            name: NSWorkspace.sessionDidBecomeActiveNotification, object: nil
        )
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
        NSWorkspace.shared.notificationCenter.removeObserver(self)
        pollingSource?.cancel()
    }

    func start() {
        guard pollingSource == nil else { return }
        let source = DispatchSource.makeTimerSource(queue: .main)
        source.schedule(deadline: .now(), repeating: .milliseconds(500), leeway: .milliseconds(100))
        source.setEventHandler { [weak self] in self?.pollPasteboard() }
        pollingSource = source
        source.resume()
        Self.logger.info("Clipboard monitoring started")
    }

    func stop() {
        guard let source = pollingSource else { return }
        pollingSource = nil
        source.cancel()
        Self.logger.info("Clipboard monitoring stopped")
    }

    @objc func handleWake() {
        if pollingSource == nil {
            Self.logger.warning("Clipboard monitor was inactive after wake; restarting")
            start()
        }
        pollPasteboard()
    }

    func pollPasteboard() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // A pause discards changes made while paused, including after resume.
        guard !settings.pauseMonitoring else { return }
        if suppressedChangeCount == currentCount {
            suppressedChangeCount = nil
            return
        }
        suppressedChangeCount = nil

        let sourceBundleID = sourceBundleIDProvider()
        guard shouldCapture(sourceBundleID: sourceBundleID), !containsProtectedType() else {
            Self.logger.debug("Clipboard change skipped by privacy policy")
            return
        }

        guard let snapshot = captureSnapshot() else { return }
        storageService.insert(snapshot: snapshot, sourceBundleID: sourceBundleID)
        NotificationCenter.default.post(name: .clipboardDidUpdate, object: nil)
        Self.logger.debug("Clipboard change captured")
    }

    private func shouldCapture(sourceBundleID: String?) -> Bool {
        guard let sourceBundleID else { return true }
        let normalized = sourceBundleID.lowercased()
        return normalized != ownBundleID && !settings.ignoredBundleIDs.contains(normalized)
    }

    private func containsProtectedType() -> Bool {
        guard let items = pasteboard.pasteboardItems else { return false }
        return items.contains { item in
            item.types.contains { Self.concealedTypes.contains($0.rawValue) }
        }
    }

    private func captureSnapshot() -> ClipboardSnapshot? {
        if let imageData = imagePayload() {
            return ClipboardSnapshot(
                kind: .image, textSubtype: nil, payload: imageData,
                contentHash: ClipboardContentClassifier.sha256Hex(imageData), createdAt: Date()
            )
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty,
           let data = text.data(using: .utf8) {
            return ClipboardSnapshot(
                kind: .text, textSubtype: ClipboardContentClassifier.classifyText(text),
                payload: data, contentHash: ClipboardContentClassifier.sha256Hex(data), createdAt: Date()
            )
        }
        return nil
    }

    private func imagePayload() -> Data? {
        guard let image = NSImage(pasteboard: pasteboard),
              let tiff = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    @objc private func handleProgrammaticWrite() {
        suppressedChangeCount = pasteboard.changeCount
    }
}
